<?php

declare(strict_types=1);

namespace Pixiekat\LuminaUiBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Stops the same patient × trial being queued twice at once.
 *
 * The "select a trial, then queue patients" screen offers one button per
 * patient row. Two rapid clicks, a double-submit, or two people working the same
 * trial would otherwise create two identical pending rows and run the EXACT
 * command twice for no benefit. The controller does check first, but a check
 * followed by an insert is not atomic — two requests can both pass the check
 * before either writes. Only the database can actually settle this.
 *
 * ── Why a PARTIAL index ─────────────────────────────────────────────────────
 * A plain UNIQUE (person_id, trial_id) would forbid re-runs and destroy the
 * history this table exists to keep. The WHERE clause is what makes the
 * constraint say the right thing:
 *
 *     "at most one IN-FLIGHT evaluation per patient × trial"
 *
 * Rows that have reached completed/failed fall out of the index entirely, so a
 * patient can accumulate as many historical results as you like, and a re-run is
 * always allowed the moment the previous attempt finishes. This is a Postgres
 * feature (partial/filtered indexes) that Doctrine cannot express in ORM
 * attributes, which is why it is written by hand here rather than generated by
 * `doctrine:migrations:diff`. Note that means a future `diff` will not try to
 * drop it — Doctrine has no metadata describing it — but it also will not know
 * to recreate it, so it must survive in this migration.
 *
 * NULL trial_id rows (search_trials_for_patients evaluations, which are not
 * trial-scoped) are excluded automatically: in Postgres a unique index never
 * conflicts on NULLs. Those runs are unaffected.
 *
 * Idempotent both ways, matching the house style — safe to re-run.
 */
final class Version20260730120000 extends AbstractMigration
{
    private const string INDEX_NAME = 'uniq_eval_active_person_trial';

    public function getDescription(): string
    {
        return 'Allow only one pending/running evaluation per patient × trial (partial unique index).';
    }

    public function up(Schema $schema): void
    {
        if (!$schema->hasTable('lumina_evaluation')) {
            $this->write('↷ lumina_evaluation table missing — skipping.');
            return;
        }

        // Doctrine's Schema object has no concept of a partial index, so it can
        // neither describe nor detect this one. IF NOT EXISTS is what keeps the
        // migration re-runnable.
        $this->write('✚ Adding partial unique index ' . self::INDEX_NAME . ' …');
        $this->addSql(sprintf(
            "CREATE UNIQUE INDEX IF NOT EXISTS %s
               ON lumina_evaluation (person_id, trial_id)
             WHERE status IN ('pending', 'running')",
            self::INDEX_NAME,
        ));
    }

    public function down(Schema $schema): void
    {
        if (!$schema->hasTable('lumina_evaluation')) {
            $this->write('↷ lumina_evaluation table missing — nothing to revert.');
            return;
        }

        $this->write('✖ Dropping index ' . self::INDEX_NAME . ' …');
        $this->addSql('DROP INDEX IF EXISTS ' . self::INDEX_NAME);
    }

    /**
     * The CREATE UNIQUE INDEX above is a single statement and Postgres runs DDL
     * transactionally, so the default wrapping transaction is fine. Declared
     * explicitly only to document that this was considered — CONCURRENTLY, which
     * you would want on a large live table, is what cannot run inside one.
     */
    public function isTransactional(): bool
    {
        return true;
    }
}
