<?php

declare(strict_types=1);

namespace Pixiekat\LuminaUiBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the application User table plus the pixiekat/symfony-common-helpers
 * tables (audit_logs, bans, vocabularies, vocabulary_terms, reset_password_request)
 * that the helper bundle's runtime services depend on.
 *
 * These tables live in lumina_db because lumina-ui's only configured migrations
 * path is this bundle — so this bundle owns the full Postgres schema for the app.
 * Narrated + idempotent (each table guarded by hasTable). Foreign keys are
 * created alongside their owning table, after the referenced table, so ordering
 * and skip-logic stay simple.
 */
final class Version20260613171339 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create users + symfony-common-helpers tables (audit_logs, bans, taxonomy, reset_password_request).';
    }

    public function up(Schema $schema): void
    {
        // Independent tables first (referenced by the FKs below).
        $this->createIfMissing($schema, 'users',
            'CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, PRIMARY KEY (id))',
            ['CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)']
        );

        $this->createIfMissing($schema, 'audit_logs',
            'CREATE TABLE audit_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(255) NOT NULL, entity_type VARCHAR(255) NOT NULL, performed_by VARCHAR(255) NOT NULL, additional_data JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))'
        );

        $this->createIfMissing($schema, 'bans',
            'CREATE TABLE bans (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ip_address VARCHAR(255) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))',
            ['CREATE INDEX idx_ip_address ON bans (ip_address)']
        );

        $this->createIfMissing($schema, 'vocabularies',
            'CREATE TABLE vocabularies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, is_enabled BOOLEAN DEFAULT true NOT NULL, locked BOOLEAN DEFAULT true NOT NULL, uuid UUID NOT NULL, PRIMARY KEY (id))',
            ['CREATE UNIQUE INDEX UNIQ_A20A445BD17F50A6 ON vocabularies (uuid)']
        );

        // Dependent tables: create table + index + FK together.
        $this->createIfMissing($schema, 'reset_password_request',
            'CREATE TABLE reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))',
            [
                'CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)',
                'ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE',
            ]
        );

        $this->createIfMissing($schema, 'vocabulary_terms',
            'CREATE TABLE vocabulary_terms (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, vocabulary_id INT NOT NULL, name VARCHAR(255) NOT NULL, weight INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))',
            [
                'CREATE INDEX IDX_BA21B29BAD0E05F6 ON vocabulary_terms (vocabulary_id)',
                'ALTER TABLE vocabulary_terms ADD CONSTRAINT FK_BA21B29BAD0E05F6 FOREIGN KEY (vocabulary_id) REFERENCES vocabularies (id) NOT DEFERRABLE',
            ]
        );
    }

    public function down(Schema $schema): void
    {
        // Drop dependents (with their FKs) before the tables they reference.
        // No CREATE SCHEMA here — we never manage the pre-existing Postgres
        // schemas (scratch, vocabulary, eval_run_001, eval_baseline).
        foreach (['vocabulary_terms', 'reset_password_request', 'vocabularies', 'bans', 'audit_logs', 'users'] as $table) {
            if ($schema->hasTable($table)) {
                $this->write(sprintf('✖ Dropping %s …', $table));
                $this->addSql(sprintf('DROP TABLE %s', $table));
            } else {
                $this->write(sprintf('↷ %s does not exist — nothing to drop.', $table));
            }
        }
    }

    /**
     * Create $table (and any follow-up DDL) only if it is not already present.
     *
     * @param string[] $thenSql additional statements (indexes, FKs) run after the create
     */
    private function createIfMissing(Schema $schema, string $table, string $ddl, array $thenSql = []): void
    {
        if ($schema->hasTable($table)) {
            $this->write(sprintf('↷ %s already exists — skipping create.', $table));
            return;
        }
        $this->write(sprintf('✚ Creating %s …', $table));
        $this->addSql($ddl);
        foreach ($thenSql as $sql) {
            $this->addSql($sql);
        }
    }
}
