<?php

declare(strict_types=1);

namespace Pixiekat\LuminaUiBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the lumina_evaluation table (one row = one patient's result from one
 * matching run) plus the messenger_messages queue table used to re-run
 * evaluations in the background.
 *
 * Written to be idempotent and chatty: every step is announced with write()
 * and guarded by a hasTable() check, so re-running against a database that
 * already has (some of) these tables prints a "skipping" line instead of
 * erroring out.
 */
final class Version20260613161642 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create lumina_evaluation table (+ messenger_messages queue table).';
    }

    public function up(Schema $schema): void
    {
        // --- lumina_evaluation -------------------------------------------------
        if ($schema->hasTable('lumina_evaluation')) {
            $this->write('↷ lumina_evaluation already exists — skipping create.');
        } else {
            $this->write('✚ Creating lumina_evaluation …');
            $this->addSql(<<<'SQL'
                CREATE TABLE lumina_evaluation (
                    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    software VARCHAR(32) NOT NULL,
                    kind VARCHAR(48) NOT NULL,
                    person_id INT NOT NULL,
                    patient_name VARCHAR(255) DEFAULT NULL,
                    trial_id INT DEFAULT NULL,
                    disease VARCHAR(128) DEFAULT NULL,
                    status VARCHAR(16) NOT NULL,
                    summary JSON DEFAULT NULL,
                    attributes JSON DEFAULT NULL,
                    command TEXT DEFAULT NULL,
                    raw_output TEXT DEFAULT NULL,
                    exit_code INT DEFAULT NULL,
                    batch_key VARCHAR(64) DEFAULT NULL,
                    ran_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                    duration_ms INT DEFAULT NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                    PRIMARY KEY (id)
                )
                SQL);
            $this->addSql('CREATE INDEX idx_eval_person ON lumina_evaluation (person_id)');
            $this->addSql('CREATE INDEX idx_eval_batch ON lumina_evaluation (batch_key)');
        }

        // --- messenger_messages (background queue) -----------------------------
        if ($schema->hasTable('messenger_messages')) {
            $this->write('↷ messenger_messages already exists — skipping create.');
        } else {
            $this->write('✚ Creating messenger_messages (Messenger background queue) …');
            $this->addSql(<<<'SQL'
                CREATE TABLE messenger_messages (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    body TEXT NOT NULL,
                    headers TEXT NOT NULL,
                    queue_name VARCHAR(190) NOT NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                    PRIMARY KEY (id)
                )
                SQL);
            $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        }
    }

    public function down(Schema $schema): void
    {
        // Drop only what exists. NB: we deliberately do NOT touch the existing
        // Postgres schemas in this database (scratch, vocabulary, eval_run_001,
        // eval_baseline) — they are not ours to manage.
        if ($schema->hasTable('lumina_evaluation')) {
            $this->write('✖ Dropping lumina_evaluation …');
            $this->addSql('DROP TABLE lumina_evaluation');
        } else {
            $this->write('↷ lumina_evaluation does not exist — nothing to drop.');
        }

        if ($schema->hasTable('messenger_messages')) {
            $this->write('✖ Dropping messenger_messages …');
            $this->addSql('DROP TABLE messenger_messages');
        } else {
            $this->write('↷ messenger_messages does not exist — nothing to drop.');
        }
    }
}
