<?php

declare(strict_types=1);

namespace Pixiekat\LuminaUiBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Adds the lumina_evaluation_batch table and replaces the loose batch_key
 * string on lumina_evaluation with a real batch_id foreign key, so batches are
 * first-class records you can list and inspect.
 *
 * Narrated + idempotent: each step checks current state (hasTable / hasColumn /
 * hasIndex) and either acts or prints a "skipping" line.
 */
final class Version20260613163317 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add lumina_evaluation_batch; swap evaluation.batch_key for a batch_id FK.';
    }

    public function up(Schema $schema): void
    {
        $eval = $schema->hasTable('lumina_evaluation') ? $schema->getTable('lumina_evaluation') : null;

        // --- 1. batch table ----------------------------------------------------
        if ($schema->hasTable('lumina_evaluation_batch')) {
            $this->write('↷ lumina_evaluation_batch already exists — skipping create.');
        } else {
            $this->write('✚ Creating lumina_evaluation_batch …');
            $this->addSql(<<<'SQL'
                CREATE TABLE lumina_evaluation_batch (
                    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    software VARCHAR(32) NOT NULL,
                    kind VARCHAR(48) NOT NULL,
                    status VARCHAR(16) NOT NULL,
                    label VARCHAR(255) DEFAULT NULL,
                    command TEXT DEFAULT NULL,
                    raw_output TEXT DEFAULT NULL,
                    summary JSON DEFAULT NULL,
                    exit_code INT DEFAULT NULL,
                    started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                    finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                    duration_ms INT DEFAULT NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                    PRIMARY KEY (id)
                )
                SQL);
        }

        // --- 2. retire the old batch_key column + its index --------------------
        if ($eval && $eval->hasIndex('idx_eval_batch')) {
            $this->write('✖ Dropping old index idx_eval_batch …');
            $this->addSql('DROP INDEX idx_eval_batch');
        }
        if ($eval && $eval->hasColumn('batch_key')) {
            $this->write('✖ Dropping old column lumina_evaluation.batch_key …');
            $this->addSql('ALTER TABLE lumina_evaluation DROP batch_key');
        }

        // --- 3. add the batch_id foreign key -----------------------------------
        if ($eval && $eval->hasColumn('batch_id')) {
            $this->write('↷ lumina_evaluation.batch_id already exists — skipping.');
        } elseif ($eval) {
            $this->write('✚ Adding lumina_evaluation.batch_id (FK → lumina_evaluation_batch) …');
            $this->addSql('ALTER TABLE lumina_evaluation ADD batch_id INT DEFAULT NULL');
            $this->addSql('ALTER TABLE lumina_evaluation ADD CONSTRAINT FK_4A9BF503F39EBE7A FOREIGN KEY (batch_id) REFERENCES lumina_evaluation_batch (id) ON DELETE SET NULL NOT DEFERRABLE');
            $this->addSql('CREATE INDEX IDX_4A9BF503F39EBE7A ON lumina_evaluation (batch_id)');
        } else {
            $this->write('⚠ lumina_evaluation table missing — run the previous migration first.');
        }
    }

    public function down(Schema $schema): void
    {
        // Reverse, guarded. We never touch the pre-existing Postgres schemas
        // (scratch, vocabulary, eval_run_001, eval_baseline).
        if ($schema->hasTable('lumina_evaluation')) {
            $eval = $schema->getTable('lumina_evaluation');

            if ($eval->hasIndex('idx_4a9bf503f39ebe7a')) {
                $this->write('✖ Dropping index IDX_4A9BF503F39EBE7A …');
                $this->addSql('DROP INDEX IDX_4A9BF503F39EBE7A');
            }
            if ($eval->hasColumn('batch_id')) {
                $this->write('✖ Dropping FK + column lumina_evaluation.batch_id …');
                $this->addSql('ALTER TABLE lumina_evaluation DROP CONSTRAINT FK_4A9BF503F39EBE7A');
                $this->addSql('ALTER TABLE lumina_evaluation DROP batch_id');
            }
            if (!$eval->hasColumn('batch_key')) {
                $this->write('✚ Restoring lumina_evaluation.batch_key …');
                $this->addSql('ALTER TABLE lumina_evaluation ADD batch_key VARCHAR(64) DEFAULT NULL');
                $this->addSql('CREATE INDEX idx_eval_batch ON lumina_evaluation (batch_key)');
            }
        }

        if ($schema->hasTable('lumina_evaluation_batch')) {
            $this->write('✖ Dropping lumina_evaluation_batch …');
            $this->addSql('DROP TABLE lumina_evaluation_batch');
        }
    }
}
